#!/usr/bin/env python3
"""Full differential suite: every table, every scenario set, physics and rules mode (optionally full).

Runs tools/emu/diff_traces.py once per (table, set, mode) as a subprocess (tables in parallel) and
prints a results table. Sets per table:
  EP1:  hand   = tools/emu/scenarios/*.json + scenarios_pathological (the hand-verified 43 + 2)
        gen    = tools/emu/scenarios/EP1/*.json (generated by scenegen.py)
  EPn:  gen    = tools/emu/scenarios/EPn/*.json
        hand   = tools/emu/scenarios/EPn/hand/*.json   (if present)
        extra  = tools/emu/scenarios/EPn/extra/*.json  (if present)

Usage (project root):
  .venv/bin/python tools/emu/run_suite.py                     # all 13 tables, physics + rules
  .venv/bin/python tools/emu/run_suite.py --tables 2,3 --modes physics,rules,full
  .venv/bin/python tools/emu/run_suite.py --markdown          # also print a Markdown table
Summaries: scratch/integrate/suite/EPn.<set>.<mode>.json; traces: scratch/integrate/traces/EPn/<set>/<mode>/.
Exit status 0 iff every scenario passes.
"""
import argparse
import json
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
PY = sys.executable


def sets_for(table):
    sc = os.path.join(HERE, 'scenarios')
    if table == 1:
        return [('hand', [sc, os.path.join(HERE, 'scenarios_pathological')]), ('gen', [os.path.join(sc, 'EP1')])]
    out = [('gen', [os.path.join(sc, f'EP{table}')])]
    for sub in ('hand', 'extra'):
        d = os.path.join(sc, f'EP{table}', sub)
        if os.path.isdir(d):
            out.append((sub, [d]))
    return out


def run_one(table, set_name, dirs, mode, outdir):
    js = os.path.join(outdir, 'suite', f'EP{table}.{set_name}.{mode}.json')
    tr = os.path.join(outdir, 'traces', f'EP{table}', set_name, mode)
    os.makedirs(os.path.dirname(js), exist_ok=True)
    cmd = [PY, os.path.join(HERE, 'diff_traces.py'), '-q', '--table', str(table), '--mode', mode,
           '--out-dir', tr, '--json', js] + dirs
    p = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    try:
        res = json.load(open(js))
    except (OSError, ValueError):
        res = [dict(name='?', status='SUITE_ERROR', ok=False, error=p.stderr[-800:])]
    return table, set_name, mode, res, p.stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--tables', default='1,2,3,4,5,6,7,8,9,10,11,12,13')
    ap.add_argument('--modes', default='physics,rules')
    ap.add_argument('--out', default=os.path.join(ROOT, 'scratch', 'integrate'))
    ap.add_argument('--jobs', type=int, default=6)
    ap.add_argument('--markdown', action='store_true')
    ap.add_argument('-v', '--verbose', action='store_true', help='print every failing scenario line')
    args = ap.parse_args()
    tables = [int(t) for t in args.tables.split(',')]
    modes = args.modes.split(',')
    jobs = [(t, s, d, m) for t in tables for (s, d) in sets_for(t) for m in modes]
    results = {}
    with ThreadPoolExecutor(max_workers=args.jobs) as ex:
        for table, set_name, mode, res, out in ex.map(lambda j: run_one(*j, args.out), jobs):
            results[(table, set_name, mode)] = res
            bad = [r for r in res if not r.get('ok')]
            if args.verbose and bad:
                for line in out.splitlines():
                    if line and not any(w in line for w in (' EXACT', 'passed (')) and 'ORIG_HANG' not in line:
                        print(f'EP{table} {set_name} {mode}: {line}')
    total = sum(len(r) for r in results.values())
    passed = sum(1 for r in results.values() for x in r if x.get('ok'))
    rows = []
    for t in tables:
        cells = []
        for m in modes:
            parts = []
            for s, _ in sets_for(t):
                res = results[(t, s, m)]
                ok = sum(1 for x in res if x.get('ok'))
                parts.append(f'{s} {ok}/{len(res)}')
            cells.append(', '.join(parts))
        rows.append((t, cells))
        fails = [(s, m, x['name'], x['status']) for (tt, s, m), res in results.items() if tt == t
                 for x in res if not x.get('ok')]
        print(f'EP{t:<2d} ' + ' | '.join(f'{m}: {c}' for m, c in zip(modes, cells)))
        for s, m, n, st in sorted(fails):
            print(f'      FAIL {m:7s} {s}/{n}: {st}')
    print(f'\n{passed}/{total} passed')
    if args.markdown:
        print('\n| Table | ' + ' | '.join(modes) + ' |')
        print('|---|' + '---|' * len(modes))
        for t, cells in rows:
            print(f'| EP{t} | ' + ' | '.join(cells) + ' |')
    json.dump({f'EP{t}.{s}.{m}': res for (t, s, m), res in results.items()},
              open(os.path.join(args.out, 'suite', 'all.json'), 'w'), indent=1, default=str)
    sys.exit(0 if passed == total else 1)


if __name__ == '__main__':
    main()
